* cleaned up notifyplugin
   cause:
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifyplugin.cpp:104:6:
   warning: unused parameter ‘configInfo’ [-Wunused-parameter]
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifyplugin.cpp:353:6:
   warning: unused parameter ‘values’ [-Wunused-parameter]
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifypluginoptionspage.cpp:73:10:
   warning: unused parameter ‘parent’ [-Wunused-parameter]
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifypluginoptionspage.cpp:451:6:
   warning: unused parameter ‘rangeStr’ [-Wunused-parameter]
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifypluginoptionspage.cpp:512:7:
   warning: unused parameter ‘oldstate’ [-Wunused-parameter]
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifypluginoptionspage.cpp:527:6:
   warning: unused parameter ‘deselected’ [-Wunused-parameter]

   implemented solution:
   fixed all of them (commented out var name)

* fixed bug in check code

   cause:
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifyplugin.cpp:
   In member function ‘void SoundNotifyPlugin::checkNotificationRule(NotificationItem*, UAVObject*)’:
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifyplugin.cpp:398:109:
   warning: suggest parentheses around comparison in operand of ‘|’ [-Wparentheses]

   implemented solution:
   this is an obvious bug that is syntactically correct but leads to a
   warning with a good compiler so this bug can be found. fixed that to use
   logical or instead of bitwise or.

* fixed bug in include file (error in compilation under Linux)

   cause:
   In file included from
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifypluginoptionspage.cpp:47:0:
   /projects/OpenPilot/git/ground/openpilotgcs/src/plugins/notify/notifytablemodel.h:86:39:
   error: reference ‘_list’ cannot be declared ‘mutable’ [-fpermissive]

   implemented solution:
   removed the mutable flag, as this is wrongly used on a reference (and
   therefore correctly causing a compile-time error